In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sanikamal/rock-paper-scissors-dataset")

print("Path to dataset files:", path)

c:\Users\mehdi\anaconda3\envs\ACV\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/sanikamal/rock-paper-scissors-dataset?dataset_version_number=1...

100%|██████████| 452M/452M [00:22<00:00, 21.0MB/s]

Extracting files...

Path to dataset files: C:\Users\mehdi\.cache\kagglehub\datasets\sanikamal\rock-paper-scissors-dataset\versions\1

In [6]:
import cv2

cam = cv2.VideoCapture(0)

if not cam.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")

counter = 0
current_frame = None

def mouse_click(event, x, y, flags, param):
    global counter, current_frame
    if event == cv2.EVENT_LBUTTONDOWN:
        counter += 1
        filename = f"data/scissors/scissors{counter}.png"
        cv2.imwrite(filename, current_frame)
        print(f"Saved {filename}")

cv2.setMouseCallback("Camera", mouse_click)

while True:
    ret, frame = cam.read()
    if not ret:
        print("Failed to grab frame")
        break

    current_frame = frame.copy()
    cv2.imshow("Camera", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()

In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
Holistic = mp.solutions.holistic.Holistic

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)

In [8]:
import os
import pickle
dataset = []
target = []
folder_path_paper = "data/paper/" 
folder_path = folder_path_paper
all_files = os.listdir(folder_path)  # lists files and folders
files_only = [f for f in all_files if os.path.isfile(os.path.join(folder_path, f))]
counter = 0
L = len(files_only)
model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

for f in files_only:
    counter += 1
    print(100*counter/L,end="\r")
    image = plt.imread(folder_path+f)
    img_model = (image[..., :3] * 255).astype(np.uint8)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
    results = model.process(img_model)
    if results.pose_landmarks is not None:
        ldk = extract_landmarks(results.pose_landmarks.landmark)
        ldk_temp = extract_landmarks(results.pose_landmarks.landmark).flatten()
        dataset.append(ldk_temp)

with open(folder_path+'dataset_paper.pkl', 'wb') as file:  # 'wb' = write binary
    pickle.dump(dataset, file)

In [8]:
results.right_hand_landmarks

In [11]:
import os
import pickle
dataset = []
target = []
gestures = ["rock","paper","scissors"]
folder_path_rock = "data/rock/" 
folder_path_scissors = "data/scissors/" 
folder_paths = [folder_path_rock,folder_path_scissors]
# folder_path = folder_path_paper
for gesture in gestures:
    folder_path = "data/"+gesture+"/"
    all_files = os.listdir(folder_path)  # lists files and folders
    files_only = [f for f in all_files 
              if os.path.isfile(os.path.join(folder_path, f)) and f.lower().endswith('.png')]

    counter = 0
    L = len(files_only)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    for f in files_only:
        counter += 1
        print(100*counter/L,end="\r")
        image = plt.imread(folder_path+f)
        img_model = (image[..., :3] * 255).astype(np.uint8)
        model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
        results = model.process(img_model)
        if results.right_hand_landmarks is not None:
            ldk_temp = extract_landmarks(results.right_hand_landmarks.landmark).flatten()
            dataset.append(ldk_temp)

    with open(folder_path+'dataset_RightHand_'+gesture+'.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(dataset, file)

:

In [10]:
results.right_hand_landmarks.landmark

[x: 0.122119345
y: 0.319025308
z: 1.1865135e-07
, x: 0.185522437
y: 0.284926057
z: -0.0177184865
, x: 0.226883456
y: 0.24733083
z: -0.0373208039
, x: 0.250067234
y: 0.229127049
z: -0.0579499565
, x: 0.273267329
y: 0.210052773
z: -0.0775989071
, x: 0.184952661
y: 0.124941185
z: -0.0293556582
, x: 0.23012042
y: 0.173848778
z: -0.0658163056
, x: 0.259506404
y: 0.221877158
z: -0.0943345129
, x: 0.28503406
y: 0.251581252
z: -0.112734973
, x: 0.144134387
y: 0.130193
z: -0.0384436101
, x: 0.209644854
y: 0.180779487
z: -0.0702716112
, x: 0.24725306
y: 0.223826885
z: -0.0855831578
, x: 0.277022541
y: 0.248032108
z: -0.0944473818
, x: 0.108671449
y: 0.16137746
z: -0.0503487922
, x: 0.174021378
y: 0.2359166
z: -0.0731117055
, x: 0.188233167
y: 0.268267453
z: -0.0731099695
, x: 0.193349153
y: 0.275238276
z: -0.0723286271
, x: 0.0837869644
y: 0.207059443
z: -0.0655160472
, x: 0.137967825
y: 0.271131545
z: -0.0778689533
, x: 0.152400494
y: 0.297455847
z: -0.074027136
, x: 0.1568432
y: 0.301144421
z: -0.0706503689
]

### Loading Individual Datasets

In [6]:

import pickle
with open("data/paper/dataset_RightHand_paper.pkl", "rb") as f:
    paper = pickle.load(f)
with open("data/rock/dataset_RightHand_rock.pkl", "rb") as f:
    rock = pickle.load(f)
with open("data/scissors/dataset_RightHand_scissors.pkl", "rb") as f:
    scissors = pickle.load(f)

In [7]:
dataset = np.concatenate((np.array(rock),np.array(paper),np.array(scissors)),axis=0)
target = ['rock']*len(rock)+['paper']*len(paper)+['scissors']*len(scissors)
columns = []
for col in range(int(dataset.shape[1]/2)):
    columns.append(f"x{col}")
    columns.append(f"y{col}")

### Converting to DataFrame and Saving to Pickle

In [8]:
import pandas as pd
data = pd.DataFrame(data= dataset,columns=columns,index = range(len(dataset)))
data["target"] = target 
data.to_pickle("dataset_total_RightHand")

In [9]:
data

,x0,y0,x1,y1,x2,y2,x3,y3,x4,y4,...,y28,x29,y29,x30,y30,x31,y31,x32,y32,target
0,0.573672,0.226715,0.597984,0.182652,0.610599,0.183127,0.622673,0.184740,0.552199,0.183838,...,1.634890,0.647217,1.674711,0.437337,1.696116,0.617394,1.756058,0.475212,1.766375,rock
1,0.623997,0.223506,0.644071,0.179155,0.654671,0.180424,0.666460,0.182407,0.605887,0.174851,...,1.709306,0.648501,1.740728,0.440305,1.769788,0.634060,1.838012,0.470953,1.854074,rock
2,0.632985,0.219469,0.650398,0.175425,0.662927,0.178246,0.673683,0.181355,0.613584,0.169122,...,1.756562,0.642226,1.805191,0.433027,1.815429,0.629188,1.903030,0.459519,1.895632,rock
3,0.626983,0.228469,0.645842,0.185668,0.658333,0.188523,0.669365,0.191473,0.609351,0.178186,...,1.663587,0.633990,1.674600,0.443113,1.720998,0.628128,1.785809,0.459212,1.803824,rock
4,0.623410,0.230267,0.644129,0.187133,0.655855,0.188868,0.667474,0.191233,0.606050,0.182138,...,1.667756,0.648643,1.667208,0.439702,1.728901,0.652137,1.775167,0.454842,1.805939,rock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,0.469636,0.009649,0.492253,-0.026859,0.508277,-0.022540,0.523764,-0.017012,0.440335,-0.032687,...,0.765515,0.610249,0.875981,0.568586,0.779457,0.703506,0.888478,0.681577,0.790849,scissors
226,0.460862,0.012855,0.485094,-0.029270,0.500350,-0.026319,0.515269,-0.022566,0.433450,-0.034566,...,0.847279,0.585552,0.886532,0.599413,0.857025,0.594121,0.897126,0.716379,0.828488,scissors
227,0.476025,0.006265,0.502443,-0.038375,0.518714,-0.036131,0.535571,-0.032033,0.449544,-0.040124,...,0.952314,0.688379,1.092020,0.753143,0.989308,0.722057,1.091257,0.854979,0.954437,scissors
228,0.500015,0.002871,0.532573,-0.060429,0.549388,-0.055734,0.566298,-0.049260,0.478579,-0.070338,...,1.122086,0.608019,1.341848,0.625679,1.113417,0.670474,1.464290,0.733060,1.213806,scissors
229,0.410261,-0.016464,0.445432,-0.056626,0.463779,-0.050972,0.480624,-0.044954,0.390921,-0.063180,...,1.104842,0.753055,1.214353,0.680734,1.128496,0.799433,1.182012,0.808300,1.004191,scissors

## Neural Network Model

In [ ]:
landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
length_inputs = len(landmarks_of_interest)

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Dropout

# Create the model
model = Sequential([
    Input((2*length_inputs,)),
    Dense(128,activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')  # Output layer for 3 classes
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',  # Use for one-hot encoded labels
    metrics=['accuracy']
)

# Model summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         2,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,611 (49.26 KB)

 Trainable params: 12,611 (49.26 KB)

 Non-trainable params: 0 (0.00 B)

In [3]:
df = pd.read_pickle("dataset_total")
landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
length_inputs = len(landmarks_of_interest)
colOI = []
for col in landmarks_of_interest:
    colOI.append(col*2)
    colOI.append(col*2+1)
colOI.append(len(df.columns)-1)
sub_df = df[df.columns[colOI]]
from sklearn.model_selection import train_test_split
X = df[df.columns[colOI[:-1]]].values
y = df[df.columns[-1]].values
dummies = pd.get_dummies(y).astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, dummies, test_size=0.15, random_state=42)

In [21]:
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(
    monitor='val_loss',      # Metric to monitor
    patience=100,              # Stop after 5 epochs of no improvement
    verbose=1,               # Print messages when stopping
    restore_best_weights=True  # Restore model weights from the epoch with the best value of monitored metric
)

In [22]:
history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks = [early_stop]
)

Epoch 1/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.4217 - val_accuracy: 0.7451 - val_loss: 0.3657
Epoch 2/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7604 - loss: 0.4189 - val_accuracy: 0.7451 - val_loss: 0.3539
Epoch 3/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.4292 - val_accuracy: 0.7451 - val_loss: 0.3967
Epoch 4/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4383 - val_accuracy: 0.7255 - val_loss: 0.4006
Epoch 5/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7569 - loss: 0.4325 - val_accuracy: 0.7451 - val_loss: 0.3710
Epoch 6/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.4255 - val_accuracy: 0.7451 - val_loss: 0.3568
Epoch 7/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4567 - val_accuracy: 0.7451 - val_loss: 0.3497
Epoch 8/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4167 - val_accuracy: 0.7451 - val_loss: 0.3700
Epoch 9/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7500 - loss: 0.4359 - val_accuracy: 0.7647 - val_loss: 0.3495
Epoch 10/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7708 - loss: 0.4331 - val_accuracy: 0.7843 - val_loss: 0.3450
Epoch 11/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4467 - val_accuracy: 0.7647 - val_loss: 0.3462
Epoch 12/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7396 - loss: 0.4351 - val_accuracy: 0.7647 - val_loss: 0.3484
Epoch 13/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7708 - loss: 0.4137 - val_accuracy: 0.7647 - val_loss: 0.3485
Epoch 14/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.4017 - val_accuracy: 0.7647 - val_loss: 0.3598
Epoch 15/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7257 - loss: 0.4245 - val_accuracy: 0.8039 - val_loss: 0.3458
Epoch 16/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7639 - loss: 0.4392 - val_accuracy: 0.7647 - val_loss: 0.3686
Epoch 17/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7535 - loss: 0.4203 - val_accuracy: 0.7647 - val_loss: 0.3455
Epoch 18/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7778 - loss: 0.3907 - val_accuracy: 0.7647 - val_loss: 0.3709
Epoch 19/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7326 - loss: 0.4477 - val_accuracy: 0.7451 - val_loss: 0.4126
Epoch 20/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7431 - loss: 0.4420 - val_accuracy: 0.7647 - val_loss: 0.3751
Epoch 21/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7361 - loss: 0.4753 - val_accuracy: 0.7843 - val_loss: 0.3458
Epoch 22/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7569 - loss: 0.4480 - val_accuracy: 0.7647 - val_loss: 0.3639
Epoch 23/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7535 - loss: 0.4297 - val_accuracy: 0.7843 - val_loss: 0.3470
Epoch 24/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7292 - loss: 0.4441 - val_accuracy: 0.7647 - val_loss: 0.3562
Epoch 25/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4350 - val_accuracy: 0.7451 - val_loss: 0.3785
Epoch 26/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4075 - val_accuracy: 0.7647 - val_loss: 0.3798
Epoch 27/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7500 - loss: 0.4359 - val_accuracy: 0.7647 - val_loss: 0.3600
Epoch 28/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7396 - loss: 0.4497 - val_accuracy: 0.8235 - val_loss: 0.3553
Epoch 29/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7431 - loss: 0.4309 - val_accuracy: 0.7647 - val_loss: 0.3590
Epoch 30/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7326 - loss: 0.4499 - val_accuracy: 0.7647 - val_loss: 0.3361
Epoch 31/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4265 - val_accuracy: 0.7451 - val_loss: 0.3520
Epoch 32/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7743 - loss: 0.4190 - val_accuracy: 0.7647 - val_loss: 0.3531
Epoch 33/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4031 - val_accuracy: 0.7647 - val_loss: 0.3300
Epoch 34/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7639 - loss: 0.4157 - val_accuracy: 0.7255 - val_loss: 0.3837
Epoch 35/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7396 - loss: 0.4261 - val_accuracy: 0.7451 - val_loss: 0.3450
Epoch 36/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4186 - val_accuracy: 0.7451 - val_loss: 0.3655
Epoch 37/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4122 - val_accuracy: 0.7451 - val_loss: 0.3520
Epoch 38/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7569 - loss: 0.4517 - val_accuracy: 0.7647 - val_loss: 0.3506
Epoch 39/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7708 - loss: 0.4313 - val_accuracy: 0.7647 - val_loss: 0.3408
Epoch 40/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7569 - loss: 0.4047 - val_accuracy: 0.7647 - val_loss: 0.3621
Epoch 41/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.4312 - val_accuracy: 0.7647 - val_loss: 0.3837
Epoch 42/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.4378 - val_accuracy: 0.7451 - val_loss: 0.4236
Epoch 43/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7569 - loss: 0.4098 - val_accuracy: 0.7451 - val_loss: 0.3495
Epoch 44/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7535 - loss: 0.4264 - val_accuracy: 0.7451 - val_loss: 0.3430
Epoch 45/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4121 - val_accuracy: 0.7451 - val_loss: 0.3536
Epoch 46/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7674 - loss: 0.4315 - val_accuracy: 0.7451 - val_loss: 0.3565
Epoch 47/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4387 - val_accuracy: 0.7843 - val_loss: 0.3788
Epoch 48/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7708 - loss: 0.4376 - val_accuracy: 0.7255 - val_loss: 0.3797
Epoch 49/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4329 - val_accuracy: 0.7647 - val_loss: 0.3456
Epoch 50/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7569 - loss: 0.4359 - val_accuracy: 0.7451 - val_loss: 0.3547
Epoch 51/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4176 - val_accuracy: 0.7647 - val_loss: 0.3468
Epoch 52/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7465 - loss: 0.4599 - val_accuracy: 0.7451 - val_loss: 0.3553
Epoch 53/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4641 - val_accuracy: 0.7647 - val_loss: 0.3516
Epoch 54/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7431 - loss: 0.4185 - val_accuracy: 0.7451 - val_loss: 0.3553
Epoch 55/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7361 - loss: 0.4507 - val_accuracy: 0.7451 - val_loss: 0.3802
Epoch 56/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7604 - loss: 0.4209 - val_accuracy: 0.7451 - val_loss: 0.3652
Epoch 57/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7604 - loss: 0.4421 - val_accuracy: 0.7647 - val_loss: 0.3832
Epoch 58/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7569 - loss: 0.4296 - val_accuracy: 0.7451 - val_loss: 0.3863
Epoch 59/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7326 - loss: 0.4430 - val_accuracy: 0.7647 - val_loss: 0.3724
Epoch 60/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7674 - loss: 0.4292 - val_accuracy: 0.7451 - val_loss: 0.4131
Epoch 61/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7361 - loss: 0.4837 - val_accuracy: 0.7255 - val_loss: 0.4048
Epoch 62/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4322 - val_accuracy: 0.7647 - val_loss: 0.3316
Epoch 63/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4045 - val_accuracy: 0.7647 - val_loss: 0.3523
Epoch 64/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7639 - loss: 0.4504 - val_accuracy: 0.7843 - val_loss: 0.3331
Epoch 65/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7708 - loss: 0.4499 - val_accuracy: 0.7451 - val_loss: 0.3616
Epoch 66/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7604 - loss: 0.4135 - val_accuracy: 0.7647 - val_loss: 0.3261
Epoch 67/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.3976 - val_accuracy: 0.7451 - val_loss: 0.3553
Epoch 68/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7396 - loss: 0.4250 - val_accuracy: 0.7451 - val_loss: 0.3660
Epoch 69/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7743 - loss: 0.3873 - val_accuracy: 0.7647 - val_loss: 0.3262
Epoch 70/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7465 - loss: 0.4595 - val_accuracy: 0.7647 - val_loss: 0.3357
Epoch 71/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7465 - loss: 0.4113 - val_accuracy: 0.7451 - val_loss: 0.3471
Epoch 72/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7639 - loss: 0.4097 - val_accuracy: 0.7451 - val_loss: 0.3762
Epoch 73/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7569 - loss: 0.4220 - val_accuracy: 0.7843 - val_loss: 0.3372
Epoch 74/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7431 - loss: 0.4281 - val_accuracy: 0.7255 - val_loss: 0.3648
Epoch 75/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7639 - loss: 0.4361 - val_accuracy: 0.7647 - val_loss: 0.3896
Epoch 76/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4149 - val_accuracy: 0.7451 - val_loss: 0.3874
Epoch 77/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4128 - val_accuracy: 0.7451 - val_loss: 0.3623
Epoch 78/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7639 - loss: 0.4049 - val_accuracy: 0.8039 - val_loss: 0.3445
Epoch 79/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.4337 - val_accuracy: 0.7451 - val_loss: 0.3954
Epoch 80/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7326 - loss: 0.4066 - val_accuracy: 0.7451 - val_loss: 0.4121
Epoch 81/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7431 - loss: 0.4509 - val_accuracy: 0.7255 - val_loss: 0.4063
Epoch 82/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7396 - loss: 0.4254 - val_accuracy: 0.7647 - val_loss: 0.3937
Epoch 83/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.3952 - val_accuracy: 0.7451 - val_loss: 0.3538
Epoch 84/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.4035 - val_accuracy: 0.7451 - val_loss: 0.3657
Epoch 85/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.4492 - val_accuracy: 0.7255 - val_loss: 0.3735
Epoch 86/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7604 - loss: 0.4115 - val_accuracy: 0.7451 - val_loss: 0.3857
Epoch 87/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7292 - loss: 0.4432 - val_accuracy: 0.7255 - val_loss: 0.3734
Epoch 88/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7361 - loss: 0.4490 - val_accuracy: 0.7255 - val_loss: 0.3957
Epoch 89/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7465 - loss: 0.4337 - val_accuracy: 0.7451 - val_loss: 0.3995
Epoch 90/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7465 - loss: 0.4635 - val_accuracy: 0.7451 - val_loss: 0.4030
Epoch 91/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7326 - loss: 0.4284 - val_accuracy: 0.7451 - val_loss: 0.3666
Epoch 92/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4160 - val_accuracy: 0.7255 - val_loss: 0.3837
Epoch 93/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7639 - loss: 0.4222 - val_accuracy: 0.7255 - val_loss: 0.4165
Epoch 94/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7639 - loss: 0.4186 - val_accuracy: 0.7255 - val_loss: 0.4210
Epoch 95/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7674 - loss: 0.4340 - val_accuracy: 0.7647 - val_loss: 0.3715
Epoch 96/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7569 - loss: 0.4691 - val_accuracy: 0.7647 - val_loss: 0.3468
Epoch 97/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7639 - loss: 0.4385 - val_accuracy: 0.7451 - val_loss: 0.3802
Epoch 98/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7465 - loss: 0.4313 - val_accuracy: 0.7647 - val_loss: 0.3742
Epoch 99/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7396 - loss: 0.4146 - val_accuracy: 0.7255 - val_loss: 0.3738
Epoch 100/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7674 - loss: 0.4206 - val_accuracy: 0.7451 - val_loss: 0.3636
Epoch 101/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7431 - loss: 0.4391 - val_accuracy: 0.7451 - val_loss: 0.3976
Epoch 102/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4027 - val_accuracy: 0.7451 - val_loss: 0.4020
Epoch 103/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7569 - loss: 0.4475 - val_accuracy: 0.7647 - val_loss: 0.3925
Epoch 104/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7569 - loss: 0.4008 - val_accuracy: 0.7647 - val_loss: 0.4145
Epoch 105/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7465 - loss: 0.4019 - val_accuracy: 0.7451 - val_loss: 0.3960
Epoch 106/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7569 - loss: 0.4456 - val_accuracy: 0.7451 - val_loss: 0.4007
Epoch 107/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7604 - loss: 0.4117 - val_accuracy: 0.7451 - val_loss: 0.3910
Epoch 108/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7812 - loss: 0.4176 - val_accuracy: 0.7451 - val_loss: 0.3768
Epoch 109/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7292 - loss: 0.4194 - val_accuracy: 0.7843 - val_loss: 0.3507
Epoch 110/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7535 - loss: 0.4112 - val_accuracy: 0.7451 - val_loss: 0.3827
Epoch 111/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.3906 - val_accuracy: 0.7451 - val_loss: 0.4064
Epoch 112/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - loss: 0.4121 - val_accuracy: 0.7255 - val_loss: 0.3884
Epoch 113/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7465 - loss: 0.4300 - val_accuracy: 0.7647 - val_loss: 0.3887
Epoch 114/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.3979 - val_accuracy: 0.7647 - val_loss: 0.3359
Epoch 115/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7431 - loss: 0.4047 - val_accuracy: 0.7255 - val_loss: 0.3790
Epoch 116/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7431 - loss: 0.4008 - val_accuracy: 0.7647 - val_loss: 0.3625
Epoch 117/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7465 - loss: 0.4151 - val_accuracy: 0.7843 - val_loss: 0.3388
Epoch 118/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7292 - loss: 0.4207 - val_accuracy: 0.7451 - val_loss: 0.3716
Epoch 119/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7535 - loss: 0.4444 - val_accuracy: 0.7647 - val_loss: 0.3521
Epoch 120/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7431 - loss: 0.4732 - val_accuracy: 0.7647 - val_loss: 0.3584
Epoch 121/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7569 - loss: 0.4296 - val_accuracy: 0.7255 - val_loss: 0.3503
Epoch 122/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7431 - loss: 0.4117 - val_accuracy: 0.7647 - val_loss: 0.3290
Epoch 123/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.4128 - val_accuracy: 0.7647 - val_loss: 0.3643
Epoch 124/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7639 - loss: 0.4093 - val_accuracy: 0.8039 - val_loss: 0.3611
Epoch 125/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.3886 - val_accuracy: 0.7647 - val_loss: 0.3430
Epoch 126/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7604 - loss: 0.4262 - val_accuracy: 0.7647 - val_loss: 0.3750
Epoch 127/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - loss: 0.3975 - val_accuracy: 0.7451 - val_loss: 0.3869
Epoch 128/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7569 - loss: 0.4197 - val_accuracy: 0.7647 - val_loss: 0.3461
Epoch 129/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7674 - loss: 0.3959 - val_accuracy: 0.7647 - val_loss: 0.3659
Epoch 130/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7708 - loss: 0.4008 - val_accuracy: 0.7647 - val_loss: 0.3532
Epoch 131/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7431 - loss: 0.3965 - val_accuracy: 0.7451 - val_loss: 0.3676
Epoch 132/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7743 - loss: 0.3866 - val_accuracy: 0.7255 - val_loss: 0.3656
Epoch 133/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7674 - loss: 0.3905 - val_accuracy: 0.7647 - val_loss: 0.3451
Epoch 134/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7431 - loss: 0.4336 - val_accuracy: 0.8039 - val_loss: 0.3399
Epoch 135/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7569 - loss: 0.3871 - val_accuracy: 0.7451 - val_loss: 0.3836
Epoch 136/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7361 - loss: 0.4307 - val_accuracy: 0.7843 - val_loss: 0.3762
Epoch 137/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7535 - loss: 0.4073 - val_accuracy: 0.7451 - val_loss: 0.3984
Epoch 138/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4110 - val_accuracy: 0.7647 - val_loss: 0.3921
Epoch 139/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7361 - loss: 0.4280 - val_accuracy: 0.7647 - val_loss: 0.3530
Epoch 140/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7535 - loss: 0.4055 - val_accuracy: 0.7647 - val_loss: 0.3668
Epoch 141/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7361 - loss: 0.4311 - val_accuracy: 0.7451 - val_loss: 0.4025
Epoch 142/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7812 - loss: 0.4027 - val_accuracy: 0.7647 - val_loss: 0.3895
Epoch 143/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7708 - loss: 0.4107 - val_accuracy: 0.7647 - val_loss: 0.4216
Epoch 144/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7569 - loss: 0.4194 - val_accuracy: 0.7451 - val_loss: 0.4130
Epoch 145/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7569 - loss: 0.4314 - val_accuracy: 0.7647 - val_loss: 0.3682
Epoch 146/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7639 - loss: 0.4271 - val_accuracy: 0.7647 - val_loss: 0.4287
Epoch 147/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7674 - loss: 0.3878 - val_accuracy: 0.7255 - val_loss: 0.3668
Epoch 148/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7847 - loss: 0.4101 - val_accuracy: 0.7255 - val_loss: 0.3728
Epoch 149/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7812 - loss: 0.4193 - val_accuracy: 0.7451 - val_loss: 0.3705
Epoch 150/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7743 - loss: 0.4062 - val_accuracy: 0.7647 - val_loss: 0.3522
Epoch 151/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.4099 - val_accuracy: 0.7255 - val_loss: 0.3976
Epoch 152/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7569 - loss: 0.4141 - val_accuracy: 0.7647 - val_loss: 0.3916
Epoch 153/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7604 - loss: 0.4194 - val_accuracy: 0.7451 - val_loss: 0.3752
Epoch 154/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7431 - loss: 0.4711 - val_accuracy: 0.7647 - val_loss: 0.3867
Epoch 155/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7257 - loss: 0.4616 - val_accuracy: 0.7059 - val_loss: 0.4032
Epoch 156/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7396 - loss: 0.4457 - val_accuracy: 0.7647 - val_loss: 0.3711
Epoch 157/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7674 - loss: 0.4337 - val_accuracy: 0.7647 - val_loss: 0.3708
Epoch 158/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7257 - loss: 0.4687 - val_accuracy: 0.7647 - val_loss: 0.3317

In [23]:
with open('model.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(model, file)

In [24]:
model.predict(X_test,verbose=0)

array([[3.76419594e-05, 5.89598145e-04, 9.99372780e-01],
       [9.97049928e-01, 8.57243489e-04, 2.09284481e-03],
       [9.96808112e-01, 8.17576190e-04, 2.37434334e-03],
       [2.44290868e-06, 4.49851364e-01, 5.50146222e-01],
       [9.99874830e-01, 3.23942550e-05, 9.27283472e-05],
       [2.34878229e-04, 4.25138026e-01, 5.74627042e-01],
       [1.12458020e-02, 3.12509865e-01, 6.76244318e-01],
       [1.84990946e-04, 3.42991110e-03, 9.96385098e-01],
       [1.44487258e-05, 3.60790896e-03, 9.96377647e-01],
       [7.27472529e-02, 3.99378330e-01, 5.27874470e-01],
       [7.70789444e-01, 9.64594260e-02, 1.32751182e-01],
       [3.19772516e-03, 3.80222410e-01, 6.16579890e-01],
       [1.43474003e-03, 8.94469582e-03, 9.89620447e-01],
       [9.99999285e-01, 1.14413929e-07, 5.65993957e-07],
       [9.97670829e-01, 8.00483220e-04, 1.52860093e-03],
       [7.57585000e-03, 4.31319326e-01, 5.61104834e-01],
       [9.95120704e-01, 1.80174073e-03, 3.07752588e-03],
       [1.84182602e-03, 3.89954299e-01, 6.08203888e-01],
       [2.28321296e-04, 1.51410385e-03, 9.98257577e-01],
       [1.16227688e-02, 4.94743645e-01, 4.93633628e-01],
       [9.29644921e-06, 1.10496185e-04, 9.99880195e-01],
       [8.19096676e-05, 4.27453548e-01, 5.72464526e-01],
       [9.99792278e-01, 4.74119042e-05, 1.60326206e-04],
       [9.96883810e-01, 1.03353546e-03, 2.08268408e-03],
       [9.99899864e-01, 2.23949846e-05, 7.77664463e-05],
       [9.84831572e-01, 4.59647924e-03, 1.05720107e-02],
       [9.98132765e-01, 5.60459623e-04, 1.30688259e-03],
       [2.99876994e-08, 5.47910213e-01, 4.52089727e-01],
       [9.95520830e-01, 1.25897420e-03, 3.22009763e-03],
       [4.83011594e-04, 4.16427642e-01, 5.83089352e-01],
       [1.10401260e-02, 4.94680375e-01, 4.94279444e-01],
       [1.01556573e-07, 4.54075217e-01, 5.45924604e-01],
       [9.97902989e-01, 6.84463652e-04, 1.41248829e-03],
       [1.52970009e-04, 4.13744003e-01, 5.86103022e-01],
       [9.95473325e-01, 1.32437691e-03, 3.20233684e-03],
       [1.06513910e-02, 4.83019322e-01, 5.06329238e-01],
       [1.94091454e-01, 3.39213237e-02, 7.71987200e-01],
       [9.69740935e-03, 2.68306702e-01, 7.21995890e-01],
       [9.98621225e-01, 4.04416875e-04, 9.74435126e-04],
       [9.94184673e-01, 2.02287943e-03, 3.79255926e-03],
       [9.94625986e-01, 1.98440487e-03, 3.38964630e-03],
       [7.57585000e-03, 4.31319326e-01, 5.61104834e-01],
       [9.96953964e-01, 1.09077839e-03, 1.95524516e-03],
       [2.63522714e-02, 5.03720582e-01, 4.69927162e-01],
       [2.80178443e-04, 2.51032263e-01, 7.48687506e-01],
       [2.60145292e-02, 2.44135171e-01, 7.29850292e-01],
       [8.69341238e-05, 9.77842486e-04, 9.98935282e-01],
       [1.69382954e-04, 1.75015500e-03, 9.98080373e-01],
       [4.24811710e-03, 3.33436459e-01, 6.62315369e-01],
       [3.17107444e-03, 3.51870477e-01, 6.44958436e-01],
       [5.78778051e-03, 3.26969445e-01, 6.67242825e-01]], dtype=float32)

## RandomForest Model (66% Accuracy)

In [73]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
params = {'n_estimators': range(100,800,100),
          'max_depth' : range(2,5,2)}
cv = RandomizedSearchCV(rf,params,verbose=2,scoring="accuracy",n_jobs=-1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42)
history = cv.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

In [74]:
pd.DataFrame(history.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.195370,0.023129,0.088505,0.006555,600,4,"{'n_estimators': 600, 'max_depth': 4}",0.706897,0.603448,0.620690,0.684211,0.614035,0.645856,0.041572,8
1,0.192483,0.021954,0.012430,0.001859,100,2,"{'n_estimators': 100, 'max_depth': 2}",0.620690,0.637931,0.689655,0.596491,0.719298,0.652813,0.045173,3
2,1.524023,0.075228,0.093853,0.009314,700,2,"{'n_estimators': 700, 'max_depth': 2}",0.620690,0.672414,0.689655,0.561404,0.701754,0.649183,0.051882,5
3,0.840734,0.050709,0.052605,0.013381,400,2,"{'n_estimators': 400, 'max_depth': 2}",0.655172,0.655172,0.706897,0.561404,0.719298,0.659589,0.055646,2
4,0.231173,0.020247,0.013568,0.004035,100,4,"{'n_estimators': 100, 'max_depth': 4}",0.724138,0.603448,0.603448,0.684211,0.596491,0.642347,0.052099,9
5,0.932329,0.055516,0.056698,0.005751,400,4,"{'n_estimators': 400, 'max_depth': 4}",0.706897,0.637931,0.637931,0.684211,0.596491,0.652692,0.038797,4
6,1.126487,0.031704,0.067970,0.007856,500,4,"{'n_estimators': 500, 'max_depth': 4}",0.706897,0.603448,0.586207,0.684211,0.614035,0.638959,0.047599,10
7,0.980709,0.092516,0.066166,0.005243,500,2,"{'n_estimators': 500, 'max_depth': 2}",0.603448,0.689655,0.706897,0.578947,0.666667,0.649123,0.049597,7
8,0.417215,0.004333,0.028461,0.001564,200,2,"{'n_estimators': 200, 'max_depth': 2}",0.603448,0.672414,0.706897,0.561404,0.701754,0.649183,0.057326,5
9,0.986080,0.029130,0.052241,0.013281,600,2,"{'n_estimators': 600, 'max_depth': 2}",0.620690,0.689655,0.706897,0.596491,0.701754,0.663097,0.045503,1

## Training XgBoost Model (66% Accuracy)

In [77]:
ybis = y
ybis[ybis=='rock'] = 0 
ybis[ybis=='paper'] = 1 
ybis[ybis=='scissors'] = 2 
X_train, X_test, y_train, y_test = train_test_split(
    X, ybis, test_size=0.15, random_state=42)

In [78]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


model = xgb.XGBClassifier(
    objective='multi:softprob',  # probabilities for each class
    num_class=3,
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42
)
model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=True
)

[0]	validation_0-mlogloss:1.04243
[1]	validation_0-mlogloss:1.01166
[2]	validation_0-mlogloss:0.98542
[3]	validation_0-mlogloss:0.95266
[4]	validation_0-mlogloss:0.92429
[5]	validation_0-mlogloss:0.90269
[6]	validation_0-mlogloss:0.88242
[7]	validation_0-mlogloss:0.85825
[8]	validation_0-mlogloss:0.84342
[9]	validation_0-mlogloss:0.82595
[10]	validation_0-mlogloss:0.80786
[11]	validation_0-mlogloss:0.79072
[12]	validation_0-mlogloss:0.77851
[13]	validation_0-mlogloss:0.76497
[14]	validation_0-mlogloss:0.75371
[15]	validation_0-mlogloss:0.74318
[16]	validation_0-mlogloss:0.73348
[17]	validation_0-mlogloss:0.72282
[18]	validation_0-mlogloss:0.71443
[19]	validation_0-mlogloss:0.70671
[20]	validation_0-mlogloss:0.70088
[21]	validation_0-mlogloss:0.69352
[22]	validation_0-mlogloss:0.68341
[23]	validation_0-mlogloss:0.67402
[24]	validation_0-mlogloss:0.66635
[25]	validation_0-mlogloss:0.66120
[26]	validation_0-mlogloss:0.65694
[27]	validation_0-mlogloss:0.64872
[28]	validation_0-mlogloss:0.64410
[29]	validation_0-mlogloss:0.64034
[30]	validation_0-mlogloss:0.63936
[31]	validation_0-mlogloss:0.63409
[32]	validation_0-mlogloss:0.62983
[33]	validation_0-mlogloss:0.62703
[34]	validation_0-mlogloss:0.62814
[35]	validation_0-mlogloss:0.62619
[36]	validation_0-mlogloss:0.62270
[37]	validation_0-mlogloss:0.62023
[38]	validation_0-mlogloss:0.61750
[39]	validation_0-mlogloss:0.61460
[40]	validation_0-mlogloss:0.61266
[41]	validation_0-mlogloss:0.61261
[42]	validation_0-mlogloss:0.61056
[43]	validation_0-mlogloss:0.61012
[44]	validation_0-mlogloss:0.60875
[45]	validation_0-mlogloss:0.60717
[46]	validation_0-mlogloss:0.60792
[47]	validation_0-mlogloss:0.60519
[48]	validation_0-mlogloss:0.60735
[49]	validation_0-mlogloss:0.60819
[50]	validation_0-mlogloss:0.60798
[51]	validation_0-mlogloss:0.60732
[52]	validation_0-mlogloss:0.60738
[53]	validation_0-mlogloss:0.60888
[54]	validation_0-mlogloss:0.60868
[55]	validation_0-mlogloss:0.61009
[56]	validation_0-mlogloss:0.60972
[57]	validation_0-mlogloss:0.61169
[58]	validation_0-mlogloss:0.61151
[59]	validation_0-mlogloss:0.61176
[60]	validation_0-mlogloss:0.61013
[61]	validation_0-mlogloss:0.61235
[62]	validation_0-mlogloss:0.61487
[63]	validation_0-mlogloss:0.61708
[64]	validation_0-mlogloss:0.61924
[65]	validation_0-mlogloss:0.62412
[66]	validation_0-mlogloss:0.62402
[67]	validation_0-mlogloss:0.62650
[68]	validation_0-mlogloss:0.62761
[69]	validation_0-mlogloss:0.63128
[70]	validation_0-mlogloss:0.63309
[71]	validation_0-mlogloss:0.63461
[72]	validation_0-mlogloss:0.63782
[73]	validation_0-mlogloss:0.63943
[74]	validation_0-mlogloss:0.64015
[75]	validation_0-mlogloss:0.64077
[76]	validation_0-mlogloss:0.64415
[77]	validation_0-mlogloss:0.64734
[78]	validation_0-mlogloss:0.64948
[79]	validation_0-mlogloss:0.65115
[80]	validation_0-mlogloss:0.65487
[81]	validation_0-mlogloss:0.65729
[82]	validation_0-mlogloss:0.65991
[83]	validation_0-mlogloss:0.66303
[84]	validation_0-mlogloss:0.66548
[85]	validation_0-mlogloss:0.66803
[86]	validation_0-mlogloss:0.66809
[87]	validation_0-mlogloss:0.66938
[88]	validation_0-mlogloss:0.67274
[89]	validation_0-mlogloss:0.67621
[90]	validation_0-mlogloss:0.67819
[91]	validation_0-mlogloss:0.67853
[92]	validation_0-mlogloss:0.68264
[93]	validation_0-mlogloss:0.68499
[94]	validation_0-mlogloss:0.68695
[95]	validation_0-mlogloss:0.68823
[96]	validation_0-mlogloss:0.68914
[97]	validation_0-mlogloss:0.69110
[98]	validation_0-mlogloss:0.69383
[99]	validation_0-mlogloss:0.69734
[100]	validation_0-mlogloss:0.69907
[101]	validation_0-mlogloss:0.70117
[102]	validation_0-mlogloss:0.70282
[103]	validation_0-mlogloss:0.70326
[104]	validation_0-mlogloss:0.70385
[105]	validation_0-mlogloss:0.70693
[106]	validation_0-mlogloss:0.70834
[107]	validation_0-mlogloss:0.71095
[108]	validation_0-mlogloss:0.71132
[109]	validation_0-mlogloss:0.71539
[110]	validation_0-mlogloss:0.71863
[111]	validation_0-mlogloss:0.72098
[112]	validation_0-mlogloss:0.72146
[113]	validation_0-mlogloss:0.72319
[114]	validation_0-mlogloss:0.72594
[115]	validation_0-mlogloss:0.72935
[116]	validation_0-mlogloss:0.73241
[117]	validation_0-mlogloss:0.73637
[118]	validation_0-mlogloss:0.73707
[119]	validation_0-mlogloss:0.73941
[120]	validation_0-mlogloss:0.74125
[121]	validation_0-mlogloss:0.74440
[122]	validation_0-mlogloss:0.74654
[123]	validation_0-mlogloss:0.74957
[124]	validation_0-mlogloss:0.75064
[125]	validation_0-mlogloss:0.75231
[126]	validation_0-mlogloss:0.75388
[127]	validation_0-mlogloss:0.75539
[128]	validation_0-mlogloss:0.75621
[129]	validation_0-mlogloss:0.75806
[130]	validation_0-mlogloss:0.75998
[131]	validation_0-mlogloss:0.76327
[132]	validation_0-mlogloss:0.76658
[133]	validation_0-mlogloss:0.77068
[134]	validation_0-mlogloss:0.77352
[135]	validation_0-mlogloss:0.77598
[136]	validation_0-mlogloss:0.77872
[137]	validation_0-mlogloss:0.78244
[138]	validation_0-mlogloss:0.78453
[139]	validation_0-mlogloss:0.78859
[140]	validation_0-mlogloss:0.79208
[141]	validation_0-mlogloss:0.79484
[142]	validation_0-mlogloss:0.79587
[143]	validation_0-mlogloss:0.79710
[144]	validation_0-mlogloss:0.79911
[145]	validation_0-mlogloss:0.79948
[146]	validation_0-mlogloss:0.80353
[147]	validation_0-mlogloss:0.80698
[148]	validation_0-mlogloss:0.80922
[149]	validation_0-mlogloss:0.80956
[150]	validation_0-mlogloss:0.81079
[151]	validation_0-mlogloss:0.81303
[152]	validation_0-mlogloss:0.81540
[153]	validation_0-mlogloss:0.81791
[154]	validation_0-mlogloss:0.81895
[155]	validation_0-mlogloss:0.82087
[156]	validation_0-mlogloss:0.82529
[157]	validation_0-mlogloss:0.82675
[158]	validation_0-mlogloss:0.82942
[159]	validation_0-mlogloss:0.83246
[160]	validation_0-mlogloss:0.83520
[161]	validation_0-mlogloss:0.83808
[162]	validation_0-mlogloss:0.84144
[163]	validation_0-mlogloss:0.84314
[164]	validation_0-mlogloss:0.84633
[165]	validation_0-mlogloss:0.84873
[166]	validation_0-mlogloss:0.85055
[167]	validation_0-mlogloss:0.85425
[168]	validation_0-mlogloss:0.85626
[169]	validation_0-mlogloss:0.85691
[170]	validation_0-mlogloss:0.85943
[171]	validation_0-mlogloss:0.86155
[172]	validation_0-mlogloss:0.86309
[173]	validation_0-mlogloss:0.86745
[174]	validation_0-mlogloss:0.87151
[175]	validation_0-mlogloss:0.87593
[176]	validation_0-mlogloss:0.87884
[177]	validation_0-mlogloss:0.88281
[178]	validation_0-mlogloss:0.88675
[179]	validation_0-mlogloss:0.89012
[180]	validation_0-mlogloss:0.89316
[181]	validation_0-mlogloss:0.89526
[182]	validation_0-mlogloss:0.89838
[183]	validation_0-mlogloss:0.90117
[184]	validation_0-mlogloss:0.90377
[185]	validation_0-mlogloss:0.90889
[186]	validation_0-mlogloss:0.91206
[187]	validation_0-mlogloss:0.91411
[188]	validation_0-mlogloss:0.91504
[189]	validation_0-mlogloss:0.91885
[190]	validation_0-mlogloss:0.92097
[191]	validation_0-mlogloss:0.92365
[192]	validation_0-mlogloss:0.92701
[193]	validation_0-mlogloss:0.92890
[194]	validation_0-mlogloss:0.93389
[195]	validation_0-mlogloss:0.93586
[196]	validation_0-mlogloss:0.93744
[197]	validation_0-mlogloss:0.93938
[198]	validation_0-mlogloss:0.93997
[199]	validation_0-mlogloss:0.94308
[200]	validation_0-mlogloss:0.94523
[201]	validation_0-mlogloss:0.94827
[202]	validation_0-mlogloss:0.94965
[203]	validation_0-mlogloss:0.95251
[204]	validation_0-mlogloss:0.95471
[205]	validation_0-mlogloss:0.95552
[206]	validation_0-mlogloss:0.95829
[207]	validation_0-mlogloss:0.95998
[208]	validation_0-mlogloss:0.96159
[209]	validation_0-mlogloss:0.96394
[210]	validation_0-mlogloss:0.96490
[211]	validation_0-mlogloss:0.96594
[212]	validation_0-mlogloss:0.96766
[213]	validation_0-mlogloss:0.97200
[214]	validation_0-mlogloss:0.97351
[215]	validation_0-mlogloss:0.97361
[216]	validation_0-mlogloss:0.97827
[217]	validation_0-mlogloss:0.98128
[218]	validation_0-mlogloss:0.98230
[219]	validation_0-mlogloss:0.98517
[220]	validation_0-mlogloss:0.98608
[221]	validation_0-mlogloss:0.99181
[222]	validation_0-mlogloss:0.99284
[223]	validation_0-mlogloss:0.99565
[224]	validation_0-mlogloss:0.99709
[225]	validation_0-mlogloss:1.00053
[226]	validation_0-mlogloss:1.00523
[227]	validation_0-mlogloss:1.00894
[228]	validation_0-mlogloss:1.01059
[229]	validation_0-mlogloss:1.01150
[230]	validation_0-mlogloss:1.01231
[231]	validation_0-mlogloss:1.01188
[232]	validation_0-mlogloss:1.01489
[233]	validation_0-mlogloss:1.01612
[234]	validation_0-mlogloss:1.01812
[235]	validation_0-mlogloss:1.02040
[236]	validation_0-mlogloss:1.02352
[237]	validation_0-mlogloss:1.02462
[238]	validation_0-mlogloss:1.02536
[239]	validation_0-mlogloss:1.02854
[240]	validation_0-mlogloss:1.02882
[241]	validation_0-mlogloss:1.03029
[242]	validation_0-mlogloss:1.03372
[243]	validation_0-mlogloss:1.03586
[244]	validation_0-mlogloss:1.03728
[245]	validation_0-mlogloss:1.03760
[246]	validation_0-mlogloss:1.03893
[247]	validation_0-mlogloss:1.04157
[248]	validation_0-mlogloss:1.04281
[249]	validation_0-mlogloss:1.04221
[250]	validation_0-mlogloss:1.04429
[251]	validation_0-mlogloss:1.04530
[252]	validation_0-mlogloss:1.04974
[253]	validation_0-mlogloss:1.05170
[254]	validation_0-mlogloss:1.05337
[255]	validation_0-mlogloss:1.05462
[256]	validation_0-mlogloss:1.05802
[257]	validation_0-mlogloss:1.05860
[258]	validation_0-mlogloss:1.06552
[259]	validation_0-mlogloss:1.06836
[260]	validation_0-mlogloss:1.07188
[261]	validation_0-mlogloss:1.07538
[262]	validation_0-mlogloss:1.07831
[263]	validation_0-mlogloss:1.07956
[264]	validation_0-mlogloss:1.08069
[265]	validation_0-mlogloss:1.08202
[266]	validation_0-mlogloss:1.08404
[267]	validation_0-mlogloss:1.08781
[268]	validation_0-mlogloss:1.09095
[269]	validation_0-mlogloss:1.09207
[270]	validation_0-mlogloss:1.09422
[271]	validation_0-mlogloss:1.09808
[272]	validation_0-mlogloss:1.09736
[273]	validation_0-mlogloss:1.10122
[274]	validation_0-mlogloss:1.10521
[275]	validation_0-mlogloss:1.10844
[276]	validation_0-mlogloss:1.11235
[277]	validation_0-mlogloss:1.11216
[278]	validation_0-mlogloss:1.11434
[279]	validation_0-mlogloss:1.11517
[280]	validation_0-mlogloss:1.11819
[281]	validation_0-mlogloss:1.12297
[282]	validation_0-mlogloss:1.12672
[283]	validation_0-mlogloss:1.12944
[284]	validation_0-mlogloss:1.13278
[285]	validation_0-mlogloss:1.13423
[286]	validation_0-mlogloss:1.13378
[287]	validation_0-mlogloss:1.13613
[288]	validation_0-mlogloss:1.13755
[289]	validation_0-mlogloss:1.14126
[290]	validation_0-mlogloss:1.14349
[291]	validation_0-mlogloss:1.14471
[292]	validation_0-mlogloss:1.14639
[293]	validation_0-mlogloss:1.14906
[294]	validation_0-mlogloss:1.15019
[295]	validation_0-mlogloss:1.15256
[296]	validation_0-mlogloss:1.15397
[297]	validation_0-mlogloss:1.15463
[298]	validation_0-mlogloss:1.15568
[299]	validation_0-mlogloss:1.15845

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None, num_class=3, ...)

In [85]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
acc = accuracy_score(y_test.astype(int), y_pred)
print(f"Validation Accuracy: {acc:.4f}")

Validation Accuracy: 0.6667

## Live Test with Webcam

In [4]:
import cv2
import mediapipe as mp
import pickle
import cv2
import mediapipe as mp
import pickle
import numpy as np   # <--- add this

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
drawing_utils = mp.solutions.drawing_utils
drawing_styles = mp.solutions.drawing_styles
gesture = ['paper', 'rock', 'scissors','None']

cap = cv2.VideoCapture(0)  # Open webcam

if not cap.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")
with open("model.pkl", "rb") as f:
    model = pickle.load(f)
ind = 3 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Flip for a mirror view
        frame = cv2.flip(frame, 1)
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make predictions
        results = holistic.process(rgb_frame)
        if results.pose_landmarks is not None:
            features = extract_landmarks(results.pose_landmarks.landmark).reshape(1, -1)
            sample = features[0:1, colOI[:-1]]   # already (1, n_features)
            # Predict using the pre-trained ML model
            prediction = model.predict(sample,verbose=0)
            if (prediction>.85).any():
                ind = np.argmax(prediction)
                print(prediction)
            else:
                ind = 3
         
        drawing_utils.draw_landmarks(
            frame,
            results.left_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )

        drawing_utils.draw_landmarks(
            frame,
            results.right_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )
        # # Display prediction
        cv2.putText(frame, f'Gesture Detected: {gesture[ind]}', (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        cv2.imshow("Camera", frame)

        if cv2.waitKey(1) & 0xFF == 27:  # ESC to quit
            break

cap.release()
cv2.destroyAllWindows()

[[0.9620116  0.0135947  0.02439377]]
[[0.9787775  0.00758281 0.01363975]]
[[0.98276097 0.00613048 0.01110859]]
[[0.9841031  0.00563335 0.01026362]]
[[0.97947663 0.00745435 0.01306905]]
[[0.97709376 0.00847818 0.01442812]]
[[0.98479307 0.00550348 0.00970353]]
[[0.98425746 0.00569497 0.01004756]]
[[0.9874814  0.00446309 0.00805545]]
[[0.98878163 0.00394221 0.00727617]]
[[0.9875896  0.00437366 0.00803674]]
[[0.9874255  0.00443482 0.00813964]]
[[0.98994714 0.00351607 0.00653686]]
[[0.9905087  0.00329041 0.00620095]]
[[0.99572337 0.00137617 0.00290039]]
[[0.99661034 0.00120622 0.00218337]]
[[9.9990129e-01 2.6088555e-05 7.2603456e-05]]
[[9.9997640e-01 5.6097524e-06 1.8051342e-05]]
[[9.9997747e-01 5.4195825e-06 1.7141238e-05]]
[[9.9997079e-01 7.2502876e-06 2.1900009e-05]]
[[9.9997389e-01 6.4445135e-06 1.9631458e-05]]
[[9.9999380e-01 1.2635031e-06 4.8577963e-06]]
[[9.9999321e-01 1.4253612e-06 5.3983426e-06]]
[[9.9998951e-01 2.3219227e-06 8.2708830e-06]]
[[9.9999464e-01 1.0911922e-06 4.2999686e-06]]
[[9.9999726e-01 5.3464407e-07 2.3163495e-06]]
[[9.9999976e-01 5.1163436e-08 2.9425462e-07]]
[[9.9999988e-01 1.3008020e-08 8.7208434e-08]]
[[1.000000e+00 6.441917e-10 5.838379e-09]]
[[1.000000e+00 7.142703e-11 8.058303e-10]]
[[1.0000000e+00 3.9899466e-11 4.5322554e-10]]
[[1.000000e+00 4.889927e-11 5.463878e-10]]
[[1.000000e+00 5.162362e-10 4.791906e-09]]
[[1.0000000e+00 3.3720654e-10 3.2576579e-09]]
[[1.000000e+00 9.954036e-10 8.619845e-09]]
[[1.000000e+00 3.945949e-09 2.981351e-08]]
[[1.0000000e+00 3.7924304e-09 2.8783807e-08]]
[[1.0000000e+00 1.6330745e-09 1.3498626e-08]]
[[1.0000000e+00 3.9795758e-09 3.0117395e-08]]
[[1.0000000e+00 5.3153064e-09 3.9152734e-08]]
[[9.9999988e-01 2.4812714e-08 1.5535942e-07]]
[[1.0000000e+00 5.0363202e-09 3.7347615e-08]]
[[1.0000000e+00 2.9310383e-09 2.2934143e-08]]
[[1.000000e+00 2.079361e-09 1.684484e-08]]
[[1.0000000e+00 3.4471246e-09 2.6560517e-08]]
[[1.0000000e+00 3.5841146e-09 2.7507326e-08]]
[[1.000000e+00 4.000176e-09 3.037185e-08]]
[[1.0000000e+00 4.4221263e-10 4.1916368e-09]]
[[1.0000000e+00 3.0139435e-10 2.9690916e-09]]
[[1.0000000e+00 2.4743127e-10 2.4871178e-09]]
[[1.0000000e+00 2.3705177e-10 2.3935767e-09]]
[[1.0000000e+00 1.6482600e-10 1.7264766e-09]]
[[1.000000e+00 3.051948e-11 3.802460e-10]]
[[1.0000000e+00 8.2827217e-12 1.1307937e-10]]
[[0.99223495 0.00251473 0.00525033]]
[[0.9266821  0.0276908  0.04562711]]
[[0.97699827 0.00814203 0.01485974]]
[[0.9826286  0.00612312 0.01124823]]
[[0.9939115  0.0019798  0.00410861]]
[[9.968375e-01 9.882611e-04 2.174246e-03]]
[[0.9950897  0.00158552 0.00332479]]
[[0.99312615 0.00228863 0.00458522]]
[[0.9937098  0.00208227 0.00420793]]
[[0.98804724 0.00409172 0.00786101]]
[[0.9802706  0.00691462 0.01281478]]
[[0.9809715  0.00663746 0.01239107]]
[[0.98243296 0.00605563 0.01151137]]
[[0.9826506  0.00599049 0.01135896]]
[[0.9692783  0.01098526 0.01973652]]
[[0.9688201  0.01115268 0.02002734]]
[[0.9842093  0.00550988 0.01028072]]
[[0.99062353 0.00319681 0.00617956]]
[[0.9911442  0.0030296  0.00582629]]
[[0.9902165  0.00336211 0.00642146]]
[[0.9908646  0.0031374  0.00599808]]
[[0.98446923 0.00550105 0.0100297 ]]
[[0.981644   0.0065842  0.01177185]]
[[0.9734428  0.00965879 0.01689849]]

mediapipe.python.solution_base.SolutionOutputs